language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head

before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

before_install:
  - sudo apt-get install subversion mercurial

script: bundle exec rake test

matrix:
  allow_failures:
    # eventmachine cann't build with rb_thread_blocking_region
    - rvm: ruby-head
